stages:
  clean:
    cmd: python src/clean.py
    deps:
    - data/raw
    outs:
    - data/clean
  features:
    cmd: python src/features.py
    deps:
    - data/clean
    - src/features.py
    outs:
    - data/featured
  model:
    cmd: python src/model.py
    deps:
    - data/featured
    - src/model.py
    outs:
    - models/untrained.joblib
    params:
    - cv
    - seed
  evaulate:
    cmd: python src/evaluate.py
    deps:
    - data/featured
    - models/untrained.joblib
    - src/evaluate.py
    params:
    - cv
    - seed
    outs:
    - models/trained.joblib
    metrics:
    - results/metrics.json:
        cache: false
    plots:
    - results/pr_curve.csv:
        cache: false
    - results/roc_curve.csv:
        cache: false
