stages:
  clean:
    cmd: python src/clean.py
    deps:
    - data/raw
    outs:
    - data/clean
  features:
    cmd: python src/features.py
    deps:
    - data/clean
    - src/features.py
    outs:
    - data/featured
